import type { Metadata } from "next"
import { PrismicPreview } from "@prismicio/next"
import { repositoryName } from "@/prismicio"
import "./globals.css"
import { Navbar } from "./components/Navbar/Navbar"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html>
      <body>
        <Navbar />
        {children}
        <PrismicPreview repositoryName={repositoryName} />
      </body>
    </html>
  )
}
