// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

/**
 * Content for Banner Item documents
 */
interface BannerItemDocumentData {
  /**
   * Image field in *Banner Item*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: banner_item.image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Title field in *Banner Item*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: banner_item.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Sub Title field in *Banner Item*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: banner_item.sub_title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  sub_title: prismic.KeyTextField;

  /**
   * Description field in *Banner Item*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: banner_item.description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * Info field in *Banner Item*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: banner_item.info
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  info: prismic.KeyTextField;

  /**
   * Button Text field in *Banner Item*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: banner_item.button_text
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  button_text: prismic.KeyTextField;

  /**
   * Button Link field in *Banner Item*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: banner_item.button_link
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  button_link: prismic.LinkField;

  /**
   * Publish End field in *Banner Item*
   *
   * - **Field Type**: Date
   * - **Placeholder**: *None*
   * - **API ID Path**: banner_item.publish_end
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#date
   */
  publish_end: prismic.DateField;

  /**
   * Position field in *Banner Item*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: banner_item.position
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  position: prismic.SelectField<"1" | "2" | "3" | "4" | "5" | "6">;
}

/**
 * Banner Item document from Prismic
 *
 * - **API ID**: `banner_item`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type BannerItemDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<BannerItemDocumentData>,
    "banner_item",
    Lang
  >;

type BasketNotificationDocumentDataSlicesSlice = never;

/**
 * Content for Checkout upsell notifications documents
 */
interface BasketNotificationDocumentData {
  /**
   * Slice Zone field in *Checkout upsell notifications*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: basket_notification.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<BasketNotificationDocumentDataSlicesSlice>;
}

/**
 * Checkout upsell notifications document from Prismic
 *
 * - **API ID**: `basket_notification`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type BasketNotificationDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<BasketNotificationDocumentData>,
    "basket_notification",
    Lang
  >;

type ClubFormModalDocumentDataSlicesSlice = never;

/**
 * Content for Club: Sign up flow documents
 */
interface ClubFormModalDocumentData {
  /**
   * Slice Zone field in *Club: Sign up flow*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: club_form_modal.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<ClubFormModalDocumentDataSlicesSlice> /**
   * Meta Description field in *Club: Sign up flow*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: club_form_modal.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Club: Sign up flow*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: club_form_modal.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Title field in *Club: Sign up flow*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: club_form_modal.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField;
}

/**
 * Club: Sign up flow document from Prismic
 *
 * - **API ID**: `club_form_modal`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ClubFormModalDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<ClubFormModalDocumentData>,
    "club_form_modal",
    Lang
  >;

type ClubPageDocumentDataSlicesSlice = never;

/**
 * Content for Club: About Page documents
 */
interface ClubPageDocumentData {
  /**
   * Club Tier field in *Club: About Page*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: club_page.club_tier
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  club_tier: prismic.ContentRelationshipField<"club_tier">;

  /**
   * Slice Zone field in *Club: About Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: club_page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<ClubPageDocumentDataSlicesSlice> /**
   * Meta Description field in *Club: About Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: club_page.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Club: About Page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: club_page.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Title field in *Club: About Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: club_page.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField;
}

/**
 * Club: About Page document from Prismic
 *
 * - **API ID**: `club_page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ClubPageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<ClubPageDocumentData>,
    "club_page",
    Lang
  >;

/**
 * Item in *Club: Tier attributes → Tier Benefits*
 */
export interface ClubTierDocumentDataTierBenefitsItem {
  /**
   * Icon field in *Club: Tier attributes → Tier Benefits*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: club_tier.tier_benefits[].icon
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  icon: prismic.ImageField<never>;

  /**
   * Title field in *Club: Tier attributes → Tier Benefits*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: club_tier.tier_benefits[].title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Description field in *Club: Tier attributes → Tier Benefits*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: club_tier.tier_benefits[].description
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  description: prismic.KeyTextField;

  /**
   * Short Description field in *Club: Tier attributes → Tier Benefits*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: club_tier.tier_benefits[].short_description
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  short_description: prismic.KeyTextField;
}

type ClubTierDocumentDataSlicesSlice = never;

/**
 * Content for Club: Tier attributes documents
 */
interface ClubTierDocumentData {
  /**
   * Tier Name field in *Club: Tier attributes*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: club_tier.tier_name
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  tier_name: prismic.KeyTextField;

  /**
   * About page field in *Club: Tier attributes*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: club_tier.about_page
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  about_page: prismic.ContentRelationshipField<"club_page">;

  /**
   * Join page field in *Club: Tier attributes*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: Connect the associated join form page
   * - **API ID Path**: club_tier.join_page
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  join_page: prismic.ContentRelationshipField<"club_form_modal">;

  /**
   * Gift page field in *Club: Tier attributes*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: Connect the associated gift form page. Leave blank if does not exist.
   * - **API ID Path**: club_tier.gift_page
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  gift_page: prismic.ContentRelationshipField<"club_form_modal">;

  /**
   * Tier Benefits field in *Club: Tier attributes*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: club_tier.tier_benefits[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  tier_benefits: prismic.GroupField<
    Simplify<ClubTierDocumentDataTierBenefitsItem>
  >;

  /**
   * Slice Zone field in *Club: Tier attributes*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: club_tier.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<ClubTierDocumentDataSlicesSlice>;
}

/**
 * Club: Tier attributes document from Prismic
 *
 * - **API ID**: `club_tier`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ClubTierDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<ClubTierDocumentData>,
    "club_tier",
    Lang
  >;

/**
 * Item in *Competition landing page → Competitions*
 */
export interface CompetitionLandingPageDocumentDataCompetitionsItem {
  /**
   * Competition page field in *Competition landing page → Competitions*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: competition_landing_page.competitions[].competition_page
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  competition_page: prismic.ContentRelationshipField<"competition_page">;
}

type CompetitionLandingPageDocumentDataSlicesSlice = never;

/**
 * Content for Competition landing page documents
 */
interface CompetitionLandingPageDocumentData {
  /**
   * Title field in *Competition landing page*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: competition_landing_page.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * Body field in *Competition landing page*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: competition_landing_page.body
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  body: prismic.RichTextField;

  /**
   * Competitions field in *Competition landing page*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: competition_landing_page.competitions[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  competitions: prismic.GroupField<
    Simplify<CompetitionLandingPageDocumentDataCompetitionsItem>
  >;

  /**
   * Slice Zone field in *Competition landing page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: competition_landing_page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<CompetitionLandingPageDocumentDataSlicesSlice> /**
   * Meta Description field in *Competition landing page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: competition_landing_page.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Competition landing page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: competition_landing_page.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Title field in *Competition landing page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: competition_landing_page.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField;
}

/**
 * Competition landing page document from Prismic
 *
 * - **API ID**: `competition_landing_page`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type CompetitionLandingPageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<CompetitionLandingPageDocumentData>,
    "competition_landing_page",
    Lang
  >;

/**
 * Content for Competition Page documents
 */
interface CompetitionPageDocumentData {
  /**
   * SEO Title field in *Competition Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: competition_page.seo_title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  seo_title: prismic.KeyTextField;

  /**
   * SEO Description field in *Competition Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: competition_page.seo_description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  seo_description: prismic.KeyTextField;

  /**
   * Competition Name field in *Competition Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: competition_page.competition_name
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  competition_name: prismic.KeyTextField /**
   * Header field in *Competition Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: competition_page.header
   * - **Tab**: Content
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  header: prismic.KeyTextField;

  /**
   * Content field in *Competition Page*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: competition_page.content
   * - **Tab**: Content
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  content: prismic.RichTextField;

  /**
   * Form ID field in *Competition Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: e.g. klaviyo-form-SxNChg
   * - **API ID Path**: competition_page.form_id
   * - **Tab**: Content
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  form_id: prismic.KeyTextField;

  /**
   * End date field in *Competition Page*
   *
   * - **Field Type**: Date
   * - **Placeholder**: *None*
   * - **API ID Path**: competition_page.end_date
   * - **Tab**: Content
   * - **Documentation**: https://prismic.io/docs/field#date
   */
  end_date: prismic.DateField;

  /**
   * Image field in *Competition Page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: competition_page.image
   * - **Tab**: Content
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Image overlay field in *Competition Page*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: competition_page.image_overlay
   * - **Tab**: Content
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  image_overlay: prismic.BooleanField /**
   * Meta Description field in *Competition Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: competition_page.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Competition Page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: competition_page.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Title field in *Competition Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: competition_page.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField;
}

/**
 * Competition Page document from Prismic
 *
 * - **API ID**: `competition_page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type CompetitionPageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<CompetitionPageDocumentData>,
    "competition_page",
    Lang
  >;

/**
 * Item in *Index Page → Images*
 */
export interface IndexPageDocumentDataImagesItem {
  /**
   * Label field in *Index Page → Images*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: index_page.images[].label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  label: prismic.KeyTextField;

  /**
   * Image field in *Index Page → Images*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: index_page.images[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Link field in *Index Page → Images*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: index_page.images[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField;
}

type IndexPageDocumentDataSlicesSlice = never;

/**
 * Content for Index Page documents
 */
interface IndexPageDocumentData {
  /**
   * Heading field in *Index Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: index_page.heading
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  heading: prismic.KeyTextField;

  /**
   * Copy field in *Index Page*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: index_page.copy
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  copy: prismic.RichTextField;

  /**
   * Images field in *Index Page*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: index_page.images[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  images: prismic.GroupField<Simplify<IndexPageDocumentDataImagesItem>>;

  /**
   * Slice Zone field in *Index Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: index_page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<IndexPageDocumentDataSlicesSlice> /**
   * Meta Description field in *Index Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: index_page.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Index Page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: index_page.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Title field in *Index Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: index_page.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField;
}

/**
 * Index Page document from Prismic
 *
 * - **API ID**: `index_page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type IndexPageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<IndexPageDocumentData>,
    "index_page",
    Lang
  >;

type IndexPagesConfigurationDocumentDataSlicesSlice = never;

/**
 * Content for Index Pages Configuration documents
 */
interface IndexPagesConfigurationDocumentData {
  /**
   * Slice Zone field in *Index Pages Configuration*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: index_pages_configuration.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<IndexPagesConfigurationDocumentDataSlicesSlice>;
}

/**
 * Index Pages Configuration document from Prismic
 *
 * - **API ID**: `index_pages_configuration`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type IndexPagesConfigurationDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<IndexPagesConfigurationDocumentData>,
    "index_pages_configuration",
    Lang
  >;

type NavSubMenuDocumentDataSlicesSlice = never;

/**
 * Content for Nav Sub Menu documents
 */
interface NavSubMenuDocumentData {
  /**
   * Slice Zone field in *Nav Sub Menu*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: nav_sub_menu.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<NavSubMenuDocumentDataSlicesSlice>;
}

/**
 * Nav Sub Menu document from Prismic
 *
 * - **API ID**: `nav_sub_menu`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type NavSubMenuDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<NavSubMenuDocumentData>,
    "nav_sub_menu",
    Lang
  >;

/**
 * Item in *Navigation Events Data → Event Group*
 */
export interface NavigationEventsDataDocumentDataEventGroupItem {
  /**
   * Location field in *Navigation Events Data → Event Group*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation_events_data.event_group[].location
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  location: prismic.KeyTextField;

  /**
   * Slug field in *Navigation Events Data → Event Group*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation_events_data.event_group[].slug
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  slug: prismic.KeyTextField;

  /**
   * Snippet field in *Navigation Events Data → Event Group*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation_events_data.event_group[].snippet
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  snippet: prismic.RichTextField;
}

/**
 * Content for Navigation Events Data documents
 */
interface NavigationEventsDataDocumentData {
  /**
   * Event Group field in *Navigation Events Data*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation_events_data.event_group[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  event_group: prismic.GroupField<
    Simplify<NavigationEventsDataDocumentDataEventGroupItem>
  >;
}

/**
 * Navigation Events Data document from Prismic
 *
 * - **API ID**: `navigation_events_data`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type NavigationEventsDataDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<NavigationEventsDataDocumentData>,
    "navigation_events_data",
    Lang
  >;

interface NavigationGenresDocumentData {}

/**
 * Navigation Genres document from Prismic
 *
 * - **API ID**: `navigation_genres`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type NavigationGenresDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<NavigationGenresDocumentData>,
    "navigation_genres",
    Lang
  >;

type OfTheYearPageDocumentDataSlicesSlice = BannerItemTestSlice;

/**
 * Content for Of the year page documents
 */
interface OfTheYearPageDocumentData {
  /**
   * Path field in *Of the year page*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: best-of
   * - **API ID Path**: of_the_year_page.path
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  path: prismic.SelectField<
    "best-of" | "about" | "browse" | "features",
    "filled"
  >;

  /**
   * Slice Zone field in *Of the year page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: of_the_year_page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<OfTheYearPageDocumentDataSlicesSlice> /**
   * Meta Description field in *Of the year page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: of_the_year_page.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Of the year page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: of_the_year_page.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Title field in *Of the year page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: of_the_year_page.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField;
}

/**
 * Of the year page document from Prismic
 *
 * - **API ID**: `of_the_year_page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type OfTheYearPageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<OfTheYearPageDocumentData>,
    "of_the_year_page",
    Lang
  >;

type ProductPageDocumentDataSlicesSlice = never;

/**
 * Content for Product Page documents
 */
interface ProductPageDocumentData {
  /**
   * Slice Zone field in *Product Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: product_page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<ProductPageDocumentDataSlicesSlice>;
}

/**
 * Product Page document from Prismic
 *
 * - **API ID**: `product_page`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ProductPageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<ProductPageDocumentData>,
    "product_page",
    Lang
  >;

/**
 * Item in *Cart Page: Recommended variants → Variants*
 */
export interface RecommendedVariantsDocumentDataVariantsItem {
  /**
   * variantId field in *Cart Page: Recommended variants → Variants*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Variant ID from Saleor eg: UHJvZHVjdFZhcmlhbnQ6MjA2NTQ2
   * - **API ID Path**: recommended_variants.variants[].variantid
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  variantid: prismic.KeyTextField;
}

/**
 * Content for Cart Page: Recommended variants documents
 */
interface RecommendedVariantsDocumentData {
  /**
   * Variants field in *Cart Page: Recommended variants*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: recommended_variants.variants[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  variants: prismic.GroupField<
    Simplify<RecommendedVariantsDocumentDataVariantsItem>
  >;
}

/**
 * Cart Page: Recommended variants document from Prismic
 *
 * - **API ID**: `recommended_variants`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type RecommendedVariantsDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<RecommendedVariantsDocumentData>,
    "recommended_variants",
    Lang
  >;

/**
 * Content for Modal: Locale redirect documents
 */
interface RedirectModalConfigurationDocumentData {
  /**
   * current locale field in *Modal: Locale redirect*
   *
   * - **Field Type**: Text
   * - **Placeholder**: You're shopping in
   * - **API ID Path**: redirect_modal_configuration.current_locale
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  current_locale: prismic.KeyTextField;

  /**
   * Switch text 1 field in *Modal: Locale redirect*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Switch to.....(currency in code
   * - **API ID Path**: redirect_modal_configuration.switch_text_1
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  switch_text_1: prismic.KeyTextField;

  /**
   * switch text continued field in *Modal: Locale redirect*
   *
   * - **Field Type**: Text
   * - **Placeholder**: ....to benefit from
   * - **API ID Path**: redirect_modal_configuration.switch_text_continued
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  switch_text_continued: prismic.KeyTextField;

  /**
   * button text remain field in *Modal: Locale redirect*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Keep shopping in
   * - **API ID Path**: redirect_modal_configuration.button_text_remain
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  button_text_remain: prismic.KeyTextField;

  /**
   * button text switch field in *Modal: Locale redirect*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Switch to shopping in
   * - **API ID Path**: redirect_modal_configuration.button_text_switch
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  button_text_switch: prismic.KeyTextField;

  /**
   * footer note field in *Modal: Locale redirect*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: redirect_modal_configuration.footer_note
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  footer_note: prismic.KeyTextField;
}

/**
 * Modal: Locale redirect document from Prismic
 *
 * - **API ID**: `redirect_modal_configuration`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type RedirectModalConfigurationDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<RedirectModalConfigurationDocumentData>,
    "redirect_modal_configuration",
    Lang
  >;

type SearchPanelDocumentDataSlicesSlice = never;

/**
 * Content for Search Panel documents
 */
interface SearchPanelDocumentData {
  /**
   * Slice Zone field in *Search Panel*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: search_panel.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<SearchPanelDocumentDataSlicesSlice>;
}

/**
 * Search Panel document from Prismic
 *
 * - **API ID**: `search_panel`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type SearchPanelDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<SearchPanelDocumentData>,
    "search_panel",
    Lang
  >;

/**
 * Item in *Store landing page → Stores*
 */
export interface StoreLandingPageDocumentDataStoresItem {
  /**
   * Store Page field in *Store landing page → Stores*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: store_landing_page.stores[].store_page
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  store_page: prismic.ContentRelationshipField<"store_page">;
}

/**
 * Content for Store landing page documents
 */
interface StoreLandingPageDocumentData {
  /**
   * Title field in *Store landing page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: store_landing_page.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Body field in *Store landing page*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: store_landing_page.body
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  body: prismic.RichTextField;

  /**
   * SEO Title field in *Store landing page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: store_landing_page.seo_title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  seo_title: prismic.KeyTextField;

  /**
   * SEO Description field in *Store landing page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: store_landing_page.seo_description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  seo_description: prismic.KeyTextField;

  /**
   * Stores field in *Store landing page*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: store_landing_page.stores[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  stores: prismic.GroupField<
    Simplify<StoreLandingPageDocumentDataStoresItem>
  > /**
   * Meta Description field in *Store landing page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: store_landing_page.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Store landing page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: store_landing_page.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Title field in *Store landing page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: store_landing_page.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField;
}

/**
 * Store landing page document from Prismic
 *
 * - **API ID**: `store_landing_page`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type StoreLandingPageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<StoreLandingPageDocumentData>,
    "store_landing_page",
    Lang
  >;

/**
 * Content for Store page documents
 */
interface StorePageDocumentData {
  /**
   * Event uid field in *Store page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: store_page.event_uid
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  event_uid: prismic.KeyTextField;

  /**
   * Name field in *Store page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: E.g. Rough Trade West
   * - **API ID Path**: store_page.name
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  name: prismic.KeyTextField;

  /**
   * Visit us field in *Store page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: e.g. Visit us
   * - **API ID Path**: store_page.visit_us
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  visit_us: prismic.KeyTextField;

  /**
   * Holiday opening times field in *Store page*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: store_page.holiday_opening_times
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  holiday_opening_times: prismic.RichTextField;

  /**
   * Opening times field in *Store page*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: store_page.opening_times
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  opening_times: prismic.RichTextField;

  /**
   * Summary field in *Store page*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: No more than 200 characters
   * - **API ID Path**: store_page.summary
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  summary: prismic.RichTextField;

  /**
   * Find us field in *Store page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: E.g. Find us
   * - **API ID Path**: store_page.find_us
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  find_us: prismic.KeyTextField;

  /**
   * Google address link field in *Store page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: e.g https://goo.gl/maps/cVhWgCDxLPsvvMAt7
   * - **API ID Path**: store_page.google_address_link
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  google_address_link: prismic.KeyTextField;

  /**
   * Google embed link field in *Store page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: embed url
   * - **API ID Path**: store_page.google_embed_link
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  google_embed_link: prismic.KeyTextField;

  /**
   * Address field in *Store page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: store_page.address
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  address: prismic.KeyTextField;

  /**
   * Contact us field in *Store page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: E.g Contact Us
   * - **API ID Path**: store_page.contact_us
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  contact_us: prismic.KeyTextField;

  /**
   * Email field in *Store page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: east@roughtrade.com
   * - **API ID Path**: store_page.email
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  email: prismic.KeyTextField;

  /**
   * Phone field in *Store page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: store_page.phone
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  phone: prismic.KeyTextField;

  /**
   * snippet field in *Store page*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: store_page.snippet
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  snippet: prismic.RichTextField;

  /**
   * Image field in *Store page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: store_page.image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never> /**
   * Meta Description field in *Store page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: store_page.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Store page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: store_page.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Title field in *Store page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: store_page.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField;
}

/**
 * Store page document from Prismic
 *
 * - **API ID**: `store_page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type StorePageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<StorePageDocumentData>,
    "store_page",
    Lang
  >;

/**
 * Content for Teaser Configuration documents
 */
interface TeaserConfigurationDocumentData {
  /**
   * Free Shipping Price field in *Teaser Configuration*
   *
   * - **Field Type**: Number
   * - **Placeholder**: Eg: '70' to denote £70
   * - **API ID Path**: teaser_configuration.free_shipping_price
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  free_shipping_price: prismic.NumberField;
}

/**
 * Teaser Configuration document from Prismic
 *
 * - **API ID**: `teaser_configuration`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type TeaserConfigurationDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<TeaserConfigurationDocumentData>,
    "teaser_configuration",
    Lang
  >;

export type AllDocumentTypes =
  | BannerItemDocument
  | BasketNotificationDocument
  | ClubFormModalDocument
  | ClubPageDocument
  | ClubTierDocument
  | CompetitionLandingPageDocument
  | CompetitionPageDocument
  | IndexPageDocument
  | IndexPagesConfigurationDocument
  | NavSubMenuDocument
  | NavigationEventsDataDocument
  | NavigationGenresDocument
  | OfTheYearPageDocument
  | ProductPageDocument
  | RecommendedVariantsDocument
  | RedirectModalConfigurationDocument
  | SearchPanelDocument
  | StoreLandingPageDocument
  | StorePageDocument
  | TeaserConfigurationDocument;

/**
 * Primary content in *BannerItemTest → Default → Primary*
 */
export interface BannerItemTestSliceDefaultPrimary {
  /**
   * image field in *BannerItemTest → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: banner_item_test.default.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * text field in *BannerItemTest → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: banner_item_test.default.primary.text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  text: prismic.RichTextField;
}

/**
 * Default variation for BannerItemTest Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BannerItemTestSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<BannerItemTestSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *BannerItemTest*
 */
type BannerItemTestSliceVariation = BannerItemTestSliceDefault;

/**
 * BannerItemTest Shared Slice
 *
 * - **API ID**: `banner_item_test`
 * - **Description**: BannerItemTest
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BannerItemTestSlice = prismic.SharedSlice<
  "banner_item_test",
  BannerItemTestSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      BannerItemDocument,
      BannerItemDocumentData,
      BasketNotificationDocument,
      BasketNotificationDocumentData,
      BasketNotificationDocumentDataSlicesSlice,
      ClubFormModalDocument,
      ClubFormModalDocumentData,
      ClubFormModalDocumentDataSlicesSlice,
      ClubPageDocument,
      ClubPageDocumentData,
      ClubPageDocumentDataSlicesSlice,
      ClubTierDocument,
      ClubTierDocumentData,
      ClubTierDocumentDataTierBenefitsItem,
      ClubTierDocumentDataSlicesSlice,
      CompetitionLandingPageDocument,
      CompetitionLandingPageDocumentData,
      CompetitionLandingPageDocumentDataCompetitionsItem,
      CompetitionLandingPageDocumentDataSlicesSlice,
      CompetitionPageDocument,
      CompetitionPageDocumentData,
      IndexPageDocument,
      IndexPageDocumentData,
      IndexPageDocumentDataImagesItem,
      IndexPageDocumentDataSlicesSlice,
      IndexPagesConfigurationDocument,
      IndexPagesConfigurationDocumentData,
      IndexPagesConfigurationDocumentDataSlicesSlice,
      NavSubMenuDocument,
      NavSubMenuDocumentData,
      NavSubMenuDocumentDataSlicesSlice,
      NavigationEventsDataDocument,
      NavigationEventsDataDocumentData,
      NavigationEventsDataDocumentDataEventGroupItem,
      NavigationGenresDocument,
      NavigationGenresDocumentData,
      OfTheYearPageDocument,
      OfTheYearPageDocumentData,
      OfTheYearPageDocumentDataSlicesSlice,
      ProductPageDocument,
      ProductPageDocumentData,
      ProductPageDocumentDataSlicesSlice,
      RecommendedVariantsDocument,
      RecommendedVariantsDocumentData,
      RecommendedVariantsDocumentDataVariantsItem,
      RedirectModalConfigurationDocument,
      RedirectModalConfigurationDocumentData,
      SearchPanelDocument,
      SearchPanelDocumentData,
      SearchPanelDocumentDataSlicesSlice,
      StoreLandingPageDocument,
      StoreLandingPageDocumentData,
      StoreLandingPageDocumentDataStoresItem,
      StorePageDocument,
      StorePageDocumentData,
      TeaserConfigurationDocument,
      TeaserConfigurationDocumentData,
      AllDocumentTypes,
      BannerItemTestSlice,
      BannerItemTestSliceDefaultPrimary,
      BannerItemTestSliceVariation,
      BannerItemTestSliceDefault,
    };
  }
}
